baseURL = 'https://nizarakbar.com'
languageCode = 'en-us'
title = 'nizarakbarm'
theme = 'hugo-coder'
defaultcontentlanguage = 'en'

paginate = 20

[markup.highlight]
style = 'github-dark'

[params]
	author = 'Nizar Akbar Meilani'
	info   = 'Linux System Administrator and DevOps'
	Description = 'My Personal Website'
	keywords = 'blog,personal'
	avatarurl = 'images/avatar.jpg'

	faviconSVG = '/img/favicon.svg'
	favicon_32 = '/img/favicon-32x32.png'
	favicon_16 = '/img/favicon-16x16.png'

	since = 2023

	enableTwemoji = true

	colorScheme = 'auto'
	hideColorschemetoggle = false

[taxonomies]
	category = 'categories'
	series = 'series'
	tag = 'tags'
	author = 'authors'

[[params.social]]
	name = 'GitHub'
	icon = 'fa fa-github fa-2x'
	weight = 1
	url = 'https://github.com/nizarakbarm/'
[[params.social]]
	name = 'LinkedIn'
	icon = 'fa fa-linkedin fa-2x'
	weight = 2
	url = 'https://www.linkedin.com/in/nizarakbarm/'

[[menu.main]]
	name = 'Blog'
	weight = 1
	url = 'posts/'
[[menu.main]]
	name = 'About'
	weight = 2
	url = 'about/'
